services:
  - type: web
    name: highcountryhomepros
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    domains:
      - highcountryhomepros.com
      - www.highcountryhomepros.com
